### ISSUE TITLE
Freya: ipv6 RPC connections break ipv4 RPC connections

### ISSUE THREAD

**Issue by jagerman** [loki-project/loki#352]
I have a 2.0.0 service node on an IPv6-connected host.  When first started, RPC requests to IPv4 localhost work fine:

```
$ curl -X POST http://127.0.0.1:22013/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: applicatin/json'
{
  "id": "0",
(etc.)
```

I can repeat the above several times without error.  I can then do the same (many times) using IPv6 localhost:

```
$ curl -X POST http://[::1]:22013/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: application/json'
{
  "id": "0",
(etc.)
```

but then if I switch back to making an IPv4 localhost request I get one of:
- the request hangs indefinitely
- `curl: (56) Recv failure: Connection reset by peer`
- `curl: (52) Empty reply from server`

Sometimes IPv4 RPC starts working again about a few attempts, sometimes it appears to be gone for good until `lokid` is restarted.

**Comment by jagerman** [comment]
Trying this on a public dual-stack host with IPv6 enabled exibits the same; I hit it with:

curl -4 -X POST http://jagerman.com:22023/json_rpc -d '{"jsonrpc":"2.0","id":"0","method":"get_info"}' -H 'Content-Type: applicatin/json'

changing the -4 to -6 and back to -4 breaks things again.  Sometimes it makes lokid segfault, too; here's a gdb backtrace of such a segfault:

```
Thread 4 "lokid" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffb7a094700 (LWP 813313)]
0x000055555578d449 in boost::asio::detail::reactive_socket_accept_op<boost::asio::basic_socket<boost::asio::ip::tcp>, boost::asio::ip::tcp, boost::_bi::bind_t<void, boost::_mfi::mf1<void, epee::net_utils::boosted_tcp_server<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<epee::net_utils::boosted_tcp_server<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >*>, boost::arg<1> (*)()> > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
(gdb) bt
#0  0x000055555578d449 in boost::asio::detail::reactive_socket_accept_op<boost::asio::basic_socket<boost::asio::ip::tcp>, boost::asio::ip::tcp, boost::_bi::bind_t<void, boost::_mfi::mf1<void, epee::net_utils::boosted_tcp_server<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >, boost::system::error_code const&>, boost::_bi::list2<boost::_bi::value<epee::net_utils::boosted_tcp_server<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >*>, boost::arg<1> (*)()> > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#1  0x000055555577a78d in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
#2  0x000055555577ae2b in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) ()
#3  0x000055555577afc1 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
#4  0x00005555557996ba in epee::net_utils::boosted_tcp_server<epee::net_utils::http::http_custom_handler<epee::net_utils::connection_context_base> >::worker_thread() ()
#5  0x00007ffff73d3f65 in ?? () from /lib/x86_64-linux-gnu/libboost_thread.so.1.67.0
#6  0x00007ffff7072f2a in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007ffff6fa5edf in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by jagerman** [comment]
Not sure if it is relevant, but this is on a Debian testing system using boost 1.67.

**Comment by jagerman** [comment]
I tried hitting it with a loop of never-ending requests on IPv4 on a freshly started daemon; no problem.  Then I switched the loop (without restarting) IPv6, another stream of requests with no problem.  Then back to IPv4 and the first request never complete.  Or sometimes if I ^C and retry a few times I get a stream of:
```
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (56) Recv failure: Connection reset by peer
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (56) Recv failure: Connection reset by peer
curl: (52) Empty reply from server
curl: (52) Empty reply from server
...
```
and sometimes these get mixed in with valid replies.  Sometimes it segfaults (as in the message above).  Sometimes the IPv4 requests start working again (after many freezes/errors) but then IPv6 requests start hanging.

**Comment by jagerman** [comment]
This seems possibly related: https://svn.boost.org/trac10/ticket/7611 and continuation at https://github.com/boostorg/asio/issues/152
